\mainmatter

# Introduction

Much data science takes place on the laptops of data scientists the world over.

However, workloads are increasingly outgrowing the capacity of laptops, data science apps and assets are becoming more and more mission-critical, and organizations are centralizing their data science functions. As a result, more and more data science is taking place in ways that interact with tools and systems traditionally within the domain of the IT group.

Sometimes this group is called DevOps, and increasingly there are standalone groups for MLOps or DataOps.

In some organizations, the DevOps group wants to support data scientists, but may not be sure how. In other organizations, data scientists are on their own to figure out how to operate.

I lead the Solutions Engineering team at RStudio. My team sits exactly in this odd space in between the data scientists and the IT/Admin/DevOps organization. We constantly sit on calls to help the IT/Admin group understand what the data scientists need and help the data scientists ask the right questions of the IT/Admin team.

This book is split into two parts. The first part is largely geared towards data scientists who are responsible for their own environments, and will provide both conceptual understanding and hands-on knowledge of how to set up your own data science workbench.

The second part is about enterprise IT/Admin functions. These are tools and technologies that are commonplace at many large organizations -- and are probably totally foreign to most data scientists. The second half of this book is less hands-on. I don't expect many readers of this book to be setting up their own LDAP server for authentication or setting up a high-availability cluster of servers.

But you might have to collaborate with your organization's IT/Admin group on such things. If you do, hopefully this book will help you understand the important questions to ask, the things you need to explain, and maybe make that relationship a little easier to manage.
