# Containers, Docker, and Orchestration {docker}

Docker is so hype right now. Get ready for layers of abstractions till your head spins.

* Docker containers are a way to isolate an app and its dependencies from the underlying host

[Graphic: Docker on underlying host]

* A docker container is easily portable from one place to another for that reason

* The "secret sauce" of docker is that containers launch REALLY quickly. 

* Lifecycle: Dockerfile -> Image -> Container

[Graphic: Docker lifecycle]

## Container Orchestration

Kubernetes (K8S) -- software for deploying and managing containers

*Helm* is the standard tool for defining kubernetes deployments.

*Helmfile* is a templating system for helm.

There are other competitors, most notably docker swarm, but K8S is by far the biggest

The line is fuzzy though -- there are container orchestration services that aren't K8S or even abstract a level up from K8S. 

[TODO: Graphic of K8S/Docker]

## Exercises
1. Put a shiny app in a container, run it on your desktop.
2. Put that container into a container registry.
3. Use a local K8S distribution to run several instances of that container.

