# Servers and the Cloud

The concept of a server is a mystery to many data scientists.

A server is just a computer that is

Servers can be hosted *on-prem*, meaning that your organization actually buys server hardware, installs it in physical racks, and puts it in a (usually) refrigerated room for people at the organization to use. This used to be the only way to have servers.

Those servers can be used in a *bare-metal* configuration, where there's a 1-1 correspondence from physical machine to computer server. This is what you're used to on your computer -- your physical machine **is** the computer you use. It's pretty rare to find organizations that make use of bare-metal servers these days.

In most organizations, the servers are virtualized. These *virtual machines (VMs)* don't necessarily have any correspondence to a physical server. Sometimes that means that many VMs are housed on a single large physical server, or that one single VM is composed of any number of pieces of physical hardware.

Even in a virtualized configuration, an organization hosting it's own server hardware is a pain for obvious reasons -- the organization has to consider issues like physical maintenance, provisioning physical servers at a rate that doesn't get too far ahead or behind the needs of the organization, and figuring out how to do geographic redundancy of servers if that's deemed necessary.

The flip of these concerns is that it's simple.

So in the mid-2000s, **cloud computing** became the buzzword of the day. It was going to solve all the problems of computing! It was going to be amazing! In short, it meant renting servers instead of buying.

These days, most organizations rent servers from one of the "big three" cloud providers -- Amazon Web Services (AWS), Microsoft Azure, or Google Cloud Platform (GCP). For these companies, their cloud provision services are enormous cash cows.

Cloud computing does solve some problems of on-prem computing -- it makes it much technically easier to provision servers on demand (in just a minute, we'll get to how to provision your own AWS server).[^servers-1] It also eliminates the need for organizations to maintain physical servers, and allows them to offload thinking about geographically locating server farms.

[^servers-1]: In many organizations, the procedures and procurement issues around provisioning new servers exist, but it's technically easy.

It also brought some problems of its own. For many tech companies, their cloud computing bills are their number 1 expense -- to the point where "helping companies understand and cut their AWS/Azure/GCP bills" is a consulting career in-and-of itself.

## Blank-as-a-Service

In 2021, everything is a service. It's no surprise that IT has gone the same way.

Back in the days when all servers were physical servers the organization owned, organizations might contract out for cleaning services or physical maintenance or even overall management of the servers and the server room. These days, cloud providers have figured out that one way to make more money is to offer higher levels of abstraction to end-users.

And many IT/Ops organizations have been more than happy to narrow the scope of their work by purchasing services from vendors, as opposed to in-housing those services.

#### Infrastructure as a Service (IaaS)

This is the original promise of cloud computing. You give the company money, and you get virtualized access to a minimally-configured server from the cloud.

This abstracted away the problem of physical server maintenance from the organization, but still leaves virtual server maintenance -- like operating system upgrades, configuring networking, and more.

#### Platform As a Service (PaaS)

Thi

[Diagram of Levels of Abstraction]

## Intro to Cloud Computing Services

Logging into any of the

Index List:

Server
SSH
Storage
Database
OS
browser
Laptop
Networking
HTTP
Cloud
