# Cloud Services and Cloud Providers

## What is the Cloud?

* General description for servers that you rent instead of buy

* 3 major cloud providers
  * AWS = Amazon
  * Azure = Microsoft
  * GCP = Google
  
## The Rise of Services

* Server/Cloud usage has gone the way of the rest of the economy -- services
* The "rent me a server + connectors" model is generally called IaaS
* Layers of abstraction on top of that -- PaaS, Saas
  * Metaphor: Cake shop
  [Diagram: Cake Shop]
  * These metaphors are helpful for general understanding...actually applying them gets really fuzzy in data science land, because something that is SaaS from IT perspective is PaaS from data scientist perspective.
    * Often find it more helpful to just categorize as IaaS/"something more abstracted".
  * These services are generally surrounded my marketing jargon -- rarely do they just explain this is ___ as a service.

https://stackoverflow.com/questions/16820336/what-is-saas-paas-and-iaas-with-examples
  
## Common Services That will be helpful to know offhand

Amazon's names aren't completely obvious. They're usually referred to by their 3-letter acronyms. Azure and Google's offerings tend to be named more literally.

## Cloud Tooling
  * Identity MGMT - IAM, Azure AD
  * Billing Mgmt

### IaaS
  * Compute - AWS EC2, Azure VMs, Google Compute Engine
  * Storage
    * file - EBS, Azure managed disk, Google Persistent Disk
    * Network drives - EFS, Azure Files, Google Filestore
    * block/blob - S3, Azure Blob Storage, Google Cloud Storage
  * Networking:
    * Private Clouds: VPC, Virtual Network, Google Virtual Private Cloud
    * DNS - Route53, Azure DNS + Traffic Manager, Google Cloud DNS

### Not IaaS
  * Container Hosting - ECS, Azure Container Instances + Container Registry
  * K8S cluster as a service - EKS, AKS, GKE
  * Run a function as a service - Lambda, Azure Functions, Google Cloud Functions
  * Database - RDS/Redshift, Azure Database, Google Cloud SQL
  * SageMaker - ML platform as a service, Azure ML, Google Notebooks

https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services#networking
https://cloud.google.com/free/docs/aws-azure-gcp-service-comparison

## Exercises
* Example of a service -- for each of the 3 providers, which services would you use if you wanted an IaaS solution, a PaaS solution?
