# Getting a real URL

\`\`\`

1.An IP address just specifies the location while a URL specifies location, protocol, and specific resource\
2.URL requires a DNS [server](http://www.differencebetween.net/technology/software-technology/difference-between-application-server-and-web-server/ "APPLICATION VS WEB") while an IP address doesn't\
3.URLs are unlimited while IP addresses are limited\
4.IP addresses and URLs have a one to many relationship\
\
Read more: [Difference Between URL and IP Address \| Difference Between](http://www.differencebetween.net/technology/internet/difference-between-url-and-ip-address/#ixzz7GHcaYyk6) <http://www.differencebetween.net/technology/internet/difference-between-url-and-ip-address/#ixzz7GHcaYyk6>

\`\`\`

In the last chapter, we talked about how network traffic knows where to go and what to do when it gets there. That's all fine and dandy, but you noticed that we spoke almost entirely in terms of IP addresses. You probably almost never work with IP addresses. Instead, we're used to visiting websites at universal resource locators (URLs), like google.com. What gives?

A URL is a more complete description of how to get to a website and what do to with the traffic than just an IP address. In this chapter, we'll discuss what a URL is and how each of the components is determined.

A URL looks like this:

$$
\overbrace{\text{http://}}^\text{protocol}\overbrace{\text{example.com}}^\text{server location}\overbrace{\text{:80}}^\text{port}\overbrace{\text{/}}^\text{resource}
$$

Now, this probably isn't what you type into your address bar in your browser. That's because modern browsers do most of this for you by default. So if you type $google.com$ into your browser's address bar, your browser will automatically assume the correct defaults for the rest. Try going to `https://google.com:443/`. What do you get?

## Using ports to get to the right service

Let's say you want to run software on a server. One of the big differences between server software, and software on your laptop is that server software needs to be able to interact with the outside world to be useful.

For example, when you want to use Microsoft Word on your computer, you just click on the button and then it's ready to go. But say I want to use RStudio Server. I don't have a desktop where I click to open RStudio Server. Instead, I go to a particular URL and I expect that RStudio will be there, ready to listen.

## Special IP Addresses and Ports

All ports below 1024 reserved.

80 - HTTP default

443 - HTTPS default

22 - SSH default

Normally, you'll see a URL written something like this:

$$
example.com
$$

It doesn't seem like this little sni

$$
\overbrace{https://}^{\text{Protocol}}\overbrace{\underbrace{www}_{\text{Subdomain}}.\underbrace{example}_{\text{Primary Domain}}.\underbrace{com}_{\text{Top-Level Domain}}}^{\text{Domain}}/\overbrace{engineering}^{\text{Path}}
$$

Even worse, IP addresses generally aren't permanent -- they can change when individual servers are replaced, or if you were to change the server architecture (say by adding and load-balancing a second instance -- see chapter XX).

Anatomy of a URL

In order to have something human-friendly and permanent, we access internet resources at uniform resource locators (URLs), like google.com, rather than an IP address.

## Getting your own domain

In the last chapter, we spent most of the time talking about server locations in terms of IP addresses. And it's true -- the "real" address of any server is its IP address. But we generally don't access websites or other resources at IP addresses -- they're hard to remember, and they can also change over time.

Instead, we generally use domains for websites, and hostnames for individual servers. We'll get into hostnames later on -- for now we're going to focus on domains.

A domain is simply a convenient alias for an IP address. The **domain name system (DNS)** is the decentralized internet phonebook that translates back and forth between domains and IP addresses. The details of how DNS resolution works are quite intricate -- but the important thing to know is that there are layers of DNS servers that eventually return an IP address to your computer for where to find your website.

From the perspective of someone trying to set up their own website, there's only one DNS server that matters to you personally -- the DNS server for your *domain name registrar*.

Domain name registrars are the companies that actually own domains. You can buy or rent one from them in order to have a domain on the internet. So let's say you take the data science server you set up in lab 1 and decide that you want to host it at a real domain.

Your first stop would be a domain name registrar where you'd find an available domain you like and pull out your credit card.

Costs for domain names vary widely. Buying a meaningless domain in a less popular top-level domain, say `ladskfmlsdf.me` can cost as little as \$3 per year. On the other hand, buying a `.com` domain that's a real word or phrase can be a few thousand dollars -- and there are articles every few years about some major company accidentally allowing their domain name to lapse and ransoming it back for stupid amounts of money.

So, conceptually, it's easy to understand how a domain comes to stand in for an IP address, with DNS being the directory that ties the two together.

### Configuring DNS to connect IP addresses and Domains

The harder part is the nitty gritty of how you accomplish that mapping yourself, which we'll get into now.

Configuration of DNS is done by way of *records*, of which there are a menagerie of types you *can* configure. Luckily, most simple configurations only need *CNAME* and *A* records.

Here's an imaginary DNS record table for the domain `example.com`:

| Path/Host | Type  | Target         |
|-----------|-------|----------------|
| `@`       | A     | `143.122.8.32` |
| `www`     | CNAME | example.com    |
| `*`       | A     | `143.122.8.33` |

Let's go through how to read this table.

Since we're configuring `example.com`, the paths/hosts in this table are relative to `example.com`.

In the first row we're configuring an A record to go to the target IP address. *A records* (or their IPv6 cousin *AAAA records*) map a domain to an actual IP address. The path `@` is a special symbol meaning exact match. So by this configuration, any traffic to `example.com` will be passed straight through to the specified IP address.

The second row deals with traffic to the `www` subdomain. *CNAME records* alias sub-domains. They're most frequently used to map sub-domains to the main domain. Since this is a `CNAME` record for example.com, this record indicates that traffic to www.example.com should be treated exactly like traffic to `example.com`. Some domain providers do automatic redirection of `www` traffic, and so this row may not be necessary in some configurations.

The last record uses the wildcard symbol `*` to send all subdomain traffic that's not already spoken for -- say `blog.example.com` or `info.example.com` directly to the IP address specified.

So what happens is that your query goes through several layers of public DNS servers to get to the DNS entry for your domain name registrar. In many cases, you'll directly configure your domain name registrar to point to your website or server -- but you also can configure the domain name registrar to point at another set of DNS servers you actually control with an *NS record*.

If you're setting up your own server, this probably isn't the case, but some large enterprises do run their own private DNS servers.

<aside>

You should always configure your domain provider as narrowly as possible -- and you should configure your website or server *first*.

#TODO: why?

</aside>

### Learning to Hate DNS

As you get deeper into using servers, you will learn to hate DNS with a fiery passion. While it's necessary so we're not running around trying to remember incomprehensible IP addresses, it's also very hard to debug as a server admin.

Let's say I've got the public domain `example.com`, and I'm taking down the server and putting up a new one. I've got to alter the public DNS record so that everyone going to `example.com` gets routed to the new IP address, and not the old one.

The thing that makes it particularly challenging is that the DNS system is decentralized. There are thousands of public DNS servers that a request could get routed to, and many of them may need updating.

Obviously, this is a difficult problem to solve, and it can take up to 24 hours for DNS changes to propagate across the network. So making changes to DNS records and checking if they've worked is kinda a guessing game of whether enough time has passed that you can conclude that your change didn't work right, or if you should just wait longer.

To add an additional layer of complexity, DNS lookups are slow, so your browser caches the results of DNS lookups it has done before. That means that it's possible you'll still get an old website even once the public DNS record has been updated. If a website has ever not worked for you and then worked when you tried a private browser, DNS caching is likely the culprit. Using a private browsing window sidesteps your main DNS cache and forces lookups to happen afresh.

### Trying it out

Go through hosting this book somewhere.

## Exercises

1.  Find a cheap domain you like and buy it.

2.  Put an EC2 server back up with the Nginx `hello-world` example.

3.  Configure your server to be available at your new domain.

    1.  Hint: In AWS, Route 53 is the service that handles incoming networking. They can serve as a domain name registrar, or you can buy a domain elsewhere and just configure the DNS using Route 53.

## Securing Traffic with `https`

When you go to a website on the internet, you'll see the URL prefixed by the `https` (though it's sometimes hidden by your browser because it's assumed). `https` is actually a mashup that is short for `http` with secure sockets layer (SSL).

These days, almost everyone actually uses the successor to SSL, transport layer security (TLS). However, because the experience of configuring TLS is identical to SSL, admins usually just talk about configuring SSL even when they mean TLS.

These days, almost every bit of internet traffic is actually `https` traffic. You will occasionally see `http` traffic inside private networks where encryption might not be as important -- but more and more organizations are requiring end-to-end use of SSL.

Securing your website or server using SSL/TLS is one of the most basic things you can do to make sure your website traffic is safe. You should always configure `https` -- full stop.

SSL/TLS security is accomplished by configuring your site or server to use a SSL certificate (often abbreviated to cert). We'll go through the details of how to get and configure an SSL certificate in this chapter -- but first a little background on how SSL/TLS works.

### How SSL/TLS Enhances Security

SSL accomplishes two things for you -- identity validation and traffic encryption.

When you go to a website, SSL/TLS is the technology that verifies that you're actually reaching the website you think you're reaching. This prevents something called a man-in-the-middle attack where a malicious actor manages to get in between the server and the client of network traffic. So, for example, you might think you're putting your bank login information into your normal bank website, but there's a hacker sitting in the middle, reading all of the traffic back and forth.

\[TODO: Image of man-in-the-middle\]

You can see this in action in your web browser. When you go to a website protected by `https`, you'll see a little lock icon to the left of the URL. That means that this website's SSL certificate matches the website and therefore your computer can verify you're actually at the website you mean to be at.

But how does your computer know what a valid SSL certificate is? Your computer has a list of trusted Certificate Authorities (CAs) who create, sell, and validate SSL/TLS certificates. So when you navigate to a website, the website sends back a digital signature. Your computer checks the signature against the indicated CA to verify that it was issued to the site in question.

\[TODO: image of SSL validation\]

The second type of scary scenario SSL prevents is a snooping/sniffing attack. Even if you're getting to the right place, your traffic travels through many different channels along the way -- routers, network switches, and more. This means that someone could theoretically look at all your traffic along the way to its meaningful destination.

When your computer gets back the digital signature to verify the site's identity, it also prompts an exchange of encryption keys. These keys are used to encrypt traffic back and forth between you and the server so anyone snooping on your message will just see garbled nonsense and not your actual content. You can think of the SSL/TLS encryption as the equivalent of writing a message on a note inside an envelope, rather than on a postcard anyone could read along the way.

### Getting a cert of your own

In order to configure your site or server with SSL, there are three steps you'll want to take: getting an SSL certificate, putting the certificate on the server, and making sure the server *only* accepts `https` traffic.

You can either buy an SSL certificate or make one yourself, using what's called a *self-signed cert*.

There are a variety of places you can buy an SSL/TLS certificate, in many cases, your domain name registrar can issue you one when you buy your domain.

When you create or buy your cert, you'll have to choose the scope. A basic SSL certificate covers just the domain itself, formally known as a fully qualified domain name (FQDN). So if you get a basic SSL certificate for `www.example.com`, `www.blog.example.com` will not be covered. You can get a *wildcard certificate* that would cover every subdomain of `*.example.com`.

<aside>

Note that basic SSL/TLS certification only validates that when you type `example.com` in your browser, that you've gotten the real `example.com`. It doesn't in any way validate who owns `example.com`, whether they're reputable, or whether you should trust them.

There are higher levels of SSL certification that do validate that, for example, the company that owns `google.com` is actually the company Google.

</aside>

But sometimes it's not feasible to buy certificates. While a basic SSL certificate for a single domain can cost \$10 per year or less, wildcard certificates will all the bells and whistles can cost thousands per year. This can get particularly expensive if you've got a lot of domains for some reason.

Moreover, there are times when you *can't* buy a certificate. If you're encrypting traffic inside a private network, you will need certificates for hosts or IP addresses that are only valid inside the private network, so there's no public CA to validate them.

There are two potential avenues to follow. In some cases, like inside a private network, you want SSL/TLS for the encryption, but don't really care about the identity validation part. In this case, it's usually possible to skip that identity validation part and automatically trust the certificate for encryption purposes.

It's also possible to create your own private CA, which would verify all your SSL certificates. This is pretty common in large organizations. At some point, every server and laptop needs to have the private CA added to its set of trusted certificate validators.

A warning: it is deceptively easy to generate and configure a self-signed SSL certificate. It's usually just a few lines of shell commands to create a certificate, and adding the certificate to your server or website is usually just a copy/paste affair.

However, it's pretty common to run into problems with self-signed certs or private CAs. Making sure the certificate chain is correct, or running into a piece of software that doesn't ignore the identity validation piece right is pretty common. This shouldn't dissuade you from using SSL/TLS. It's an essential, and basic, component of any security plan -- but using a self-signed cert probably isn't as easy as it seems.

When you configure your site or server, there will likely be an option to redirect all `http` traffic to `https` traffic. If your server or site is open to the internet, you should set this option.
