# IT and Data Science Workflows

* Well developed patterns for putting things into prod in IT
* Data science starting to adopt, but not exactly the same

## Dev/Test/Prod

* Classic workflow - three precise mirrors
  * Do dev work in dev env
  * Test for functionality and with users (User Acceptance Testing - UAT)
  * Deploy to production environment
  
* Doesn't quite work for data science
* Often, dev is a distinct (RStudio IDE/Jupyter)
  * Because more exploratory than pure software development
* Test/Prod can be on one server or multiple, depending on org

* If you're managing your own Data Science server, you'll want an additional staging environment -- unrelated to app changes, purely for IT changes

[Graphic: deploying app changes and server changes]

## Cattle, Not Pets

* Manual promotion from place to place = bad
  * State maintenance
  * Drift
* Cattle not Pets
* Infrastructure as code tooling
  * Terraform
  * AWS CFN, Azure Resource Manager, Google Cloud Deployment Manager
  * Chef
  * Puppet
  * Saltstack
  * Ansible
  * Docker
  * Vagrant
  * Helm/Helmfile
  
## How Does Stuff Actually Get Deployed

[Graphic: CI/CD deployment into test/prod]

* CI/CD - Jenkins, Travis, GHA
* Powered by Git, mostly
* Intro to using GHA

## Exercises

1. Create something and add GHA integration [TODO: What to use as example?]
2. Stand up some virtual environments using ___ [TODO: Which ones to try?]
