# Scaling 

## Types of Scaling

* Vertical Scaling -- just make the server bigger
* Horizontal -- add more parallel servers
  * Sometimes called load-balancing
* Reliability - or high-availability (HA)
  * Make sure the service doesn't go down (or less often)
  * Eliminate single-points-of-failure
  * Really hard to do all the way -- spectrum of completeness + difficulty
* Health Checks/Heartbeats -- periodic checkins to ensure server/service healthy
  
## Load-Balancing configurations

[Graphic: network diagram of lb-config]

* Active/Active - all servers accept traffic
  * Single vs multiple masters

* Active/Passive (fallover/failover) - secondary server, remains inert until 2nd one fails

* Disaster Recovery - backup data to another disk -- somewhat slower resumption of service

## Adding servers in real time

* If you find yourself under heavy load, you'll want to add more servers
* If you're using infrastructure as code tooling, this is easy
* It's also easy if using some sort of docker orchestration, as the underlying hosts are all the same from the perspective of docker/K8S
