---
editor_options: 
  markdown: 
    wrap: 72
---

# Useful Shell Commands

Unlike on your Windows or Mac desktop, most work on a server is done via
the shell -- an interactive text-based prompt. If you master the set of
commands below, you'll always feel like a real hacker.

In most cases, you'll be using the `bash` shell. If you're using Linux
or Mac, that'll be the default. Below, I'm intentionally mixing up bash
commands and Linux system commands because they're useful. If you know
the difference and are pedantic enough to care, this list isn't for you
anyway.

## Miscellaneous Symbols

+-----------------+----------------+-----------------+-----------------+
| Symbol          | What it is     | Helpful options | Example         |
+=================+================+=================+=================+
| `/`             | system root    |                 |                 |
+-----------------+----------------+-----------------+-----------------+
| `~`             | your home      |                 | `echo ~`        |
|                 | directory      |                 |                 |
|                 |                |                 | `/              |
|                 |                |                 | home/alex.gold` |
+-----------------+----------------+-----------------+-----------------+
| `.`             | current        |                 |                 |
|                 | working        |                 |                 |
|                 | directory      |                 |                 |
+-----------------+----------------+-----------------+-----------------+
| `man`           | **man**ual     |                 |                 |
+-----------------+----------------+-----------------+-----------------+
| `|`             | the pipe       |                 |                 |
+-----------------+----------------+-----------------+-----------------+
| `echo`          |                |                 |                 |
+-----------------+----------------+-----------------+-----------------+
| `$`             |                |                 |                 |
+-----------------+----------------+-----------------+-----------------+
| sudo            |                |                 |                 |
+-----------------+----------------+-----------------+-----------------+
| su              |                |                 |                 |
+-----------------+----------------+-----------------+-----------------+

## Moving yourself and your files

+--------+----------------+---------------------+---------------------+
| C      | What it does   | Helpful options     | Example             |
| ommand |                |                     |                     |
+========+================+=====================+=====================+
| `pwd`  | **p**rint      |                     | `$ pwd`             |
|        | **w**orking    |                     |                     |
|        | **d**irectory  |                     | `/Users/alex.gold/` |
+--------+----------------+---------------------+---------------------+
| `cd`   | **c**hange     |                     | `$ cd ~/Documents`  |
|        | **d**irectory  |                     |                     |
+--------+----------------+---------------------+---------------------+
| `ls`   | **l**i**s**t   | `-l` - format as    | `$ ls .`            |
|        |                | list                |                     |
|        |                |                     | `$ ls -la`          |
|        |                | `-a` - all (include |                     |
|        |                | hidden files)       |                     |
+--------+----------------+---------------------+---------------------+
| `rm`   | **r**e**m**ove | `-r` - recursively  | `$ rm old_doc`      |
|        | (delete        | (a directory and    |                     |
|        | permanently!)  | included files)     | `rm -rf old_docs/`  |
|        |                |                     |                     |
|        |                | `-f` - force -      | BE VERY CAREFUL     |
|        |                | don't ask for each  | WITH `-rf`          |
|        |                | file                |                     |
+--------+----------------+---------------------+---------------------+
| `cp`   | **c**o**p**y   |                     |                     |
+--------+----------------+---------------------+---------------------+
| `mv`   | **m**o**v**e   |                     |                     |
+--------+----------------+---------------------+---------------------+
| `      |                |                     |                     |
| chmod` |                |                     |                     |
+--------+----------------+---------------------+---------------------+

## Checking out Files

Often useful in server contexts for reading log files.

+--------+----------------+---------------------+---------------------+
| C      | What it does   | Helpful options     | Example             |
| ommand |                |                     |                     |
+========+================+=====================+=====================+
| `cat`  |                |                     |                     |
+--------+----------------+---------------------+---------------------+
| `less` |                |                     |                     |
+--------+----------------+---------------------+---------------------+
| `tail` |                | -f                  |                     |
+--------+----------------+---------------------+---------------------+
| `grep` |                |                     |                     |
+--------+----------------+---------------------+---------------------+
| `tar`  |                |                     |                     |
+--------+----------------+---------------------+---------------------+

## Checking out Server Activity

+--------+----------------+---------------------+---------------------+
| C      | What it does   | Helpful options     | Example             |
| ommand |                |                     |                     |
+========+================+=====================+=====================+
| `df`   |                | -h                  |                     |
+--------+----------------+---------------------+---------------------+
| `top`  |                |                     |                     |
+--------+----------------+---------------------+---------------------+
| `ps`   |                |                     |                     |
+--------+----------------+---------------------+---------------------+
| `lsof` |                |                     |                     |
+--------+----------------+---------------------+---------------------+

## Checking out Networking

+--------+----------------+---------------------+---------------------+
| C      | What it does   | Helpful options     | Example             |
| ommand |                |                     |                     |
+========+================+=====================+=====================+
| `ping` |                |                     |                     |
+--------+----------------+---------------------+---------------------+
| `ne    |                |                     |                     |
| tstat` |                |                     |                     |
+--------+----------------+---------------------+---------------------+
| `curl` |                |                     |                     |
+--------+----------------+---------------------+---------------------+

## User Management

+--------+----------------+---------------------+---------------------+
| C      | What it does   | Helpful options     | Example             |
| ommand |                |                     |                     |
+========+================+=====================+=====================+
| `w     |                |                     |                     |
| hoami` |                |                     |                     |
+--------+----------------+---------------------+---------------------+
| `p     |                |                     |                     |
| asswd` |                |                     |                     |
+--------+----------------+---------------------+---------------------+
| `us    |                |                     |                     |
| eradd` |                |                     |                     |
+--------+----------------+---------------------+---------------------+

