\cleardoublepage 

# (APPENDIX) Appendix {-}

# More to Say

Yeah! I have finished my book, but I have more to say about some topics. Let me explain them in this appendix.

To know more about **bookdown**, see https://bookdown.org.

## An aside on open source

I personally find open source software fascinating. As a data scientist working in R or Python, you might care about the water you're swimming in. If you don't, that's fine too and you don't need to worry about this. Feel free to skip ahead.

Unlike Mac OS or Windows, Linux is open source. You've probably already heard of open source licensing, as the R and Python languages themselves, as well as the packages and libraries you use with them, are open source licensed.

What it means to be open sourced is that if you want to read the code for Windows or Mac OS, you have to go get a job at Microsoft or Apple and join a team working on those code bases. In contrast, a quick google search will allow you to read the source code for Linux, R, Python, pandas, or the tidyverse.

Reading source code is one thing, but the fascinating (and controversial) part of open source licensing is when it comes to reuse. There is a menagerie of different types of open source licenses. The differences between open source licenses mainly concern how permissible they are in terms of reuse of the software. In contrast to the permissibility of standard copyright, which is about whether and how you're allowed to create derivative works, the variations in open source licenses are about how you're allowed to license permissive works.

The most permissive open source licenses basically amount to "do whatever you want with my software", while more restrictive ones, often called copyleft, require that any derivative works also be open source. There have even been discussions recently of creating open source licenses that restrict the usage of the software along certain ethical dimensions.

In a "traditional" software company, software is written by the company, and the software is then sold to make money. Increasingly, companies are writing open source software and monetizing this business in a number of different ways.

Many versions of Linux are free, while others have an associated cost. Even more confusingly, there are several distributions that share a common codebase, where some are free and some paid. For example, Red Hat, the company behind the paid RHEL are also the primary maintainers of CentOS, and CentOS is the basis for Amazon Linux, which you can get on an Amazon Web Services Server (more on that in a moment).

## Headers

When you make a request to a server, metadata about the request is embedded. This metadata doesn't appear explicitly in the URL at all, but is included in every piece of internet traffic, and is extremely important for the way the internet and other computer networks work.

One example of a header you use a lot in your daily life is the User-Agent header. This header identifies the type of computer a request is coming from – and is used to determine whether you are accessing from a phone and should get a mobile-friendly version of a website.

You can see this metadata when you visit a website by opening the developer tools panel in your browser. In Chrome, you can go to View > Developer > Developer Tools > Network. Then, when you navigate to a website, you'll see every bit of traffic back and forth. If you click on any of the lines, you can see all the headers that are being used to identify the traffic back and forth.
