project:
  type: book

book:
  title: "DevOps for Data Science"
  author: "Alex K Gold"
  page-footer:
    left: "Copyright 2022, Alex K Gold"
    right:
      - icon: github
        href: https://github.com/akgold/do4ds
      - icon: twitter
        href: https://twitter.com/alexkgold
  search: true
  site-url: https://do4ds.com
  repo-url: https://github.com/akgold/do4ds
  repo-actions: [edit]
  sharing: [twitter, facebook]
  google-analytics: "G-BTSMMRMH08"
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - part: chapters/sec1/1-0-sec-intro.qmd
      chapters:
      - chapters/sec1/1-1-code-promotion.qmd
      - chapters/sec1/1-2-env-as-code.qmd
      - chapters/sec1/1-3-proj-components.qmd
      - chapters/sec1/1-4-monitor-log.qmd
      - chapters/sec1/1-5-docker.qmd
    - part: chapters/sec2/2-0-sec-intro.qmd
      chapters:
      - chapters/sec2/2-1-cloud.qmd
      - chapters/sec2/2-2-cmd-line.qmd
      - chapters/sec2/2-3-linux-admin.qmd
      - chapters/sec2/2-4-understanding-traffic.qmd
      - chapters/sec2/2-5-servers.qmd
    - part: chapters/sec3/3-0-sec-intro.qmd
      chapters:
      - chapters/sec3/3-1-env-promote.qmd
      - chapters/sec3/3-2-secure-networking.qmd
      - chapters/sec3/3-3-auth.qmd
      - chapters/sec3/3-4-scaling.qmd


  appendices:
    - chapters/append/docker-cheatsheet.qmd

#bibliography: references.bib

format:
  html:
    theme: flatly

editor: visual

