project:
  type: book

book:
  title: "DevOps for Data Science"
  author: "Alex K Gold"
  page-footer:
    left: "Copyright 2022, Alex K Gold"
    right:
      - icon: github
        href: https://github.com/akgold/do4ds
      - icon: twitter
        href: https://twitter.com/alexkgold
  search: true
  site-url: https://do4ds.com
  repo-url: https://github.com/akgold/do4ds
  repo-actions: [edit]
  sharing: [twitter, facebook]
  google-analytics: "G-EQR1RYSHQK"
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - part: chapters/sec1/1-0-sec-intro.qmd
      chapters:
      - chapters/sec1/1-1-env-as-code.qmd
      - chapters/sec1/1-2-proj-arch.qmd
      - chapters/sec1/1-3-data-access.qmd
      - chapters/sec1/1-4-monitor-log.qmd
      - chapters/sec1/1-5-deployments.qmd
    - part: chapters/sec2/2-0-sec-intro.qmd
      chapters:
      - chapters/sec2/2-4-docker.qmd
    - part: chapters/sec3/3-0-sec-intro.qmd
      chapters:
      - chapters/sec3/3-1-servers.qmd
      - chapters/sec3/3-2-cmd-line.qmd
      - chapters/sec3/3-3-file-users.qmd
      - chapters/sec3/3-4-ssh.qmd
      - chapters/sec3/3-5-app-admin.qmd
      - chapters/sec3/3-6-networking.qmd
      - chapters/sec3/3-7-dns.qmd
      - chapters/sec3/3-8-ssl.qmd
      - chapters/sec3/3-9-resources.qmd
      - chapters/sec3/3-10-troubleshoot.qmd
    - part: chapters/sec4/4-0-sec-intro.qmd
      chapters:
      - chapters/sec4/4-1-os-ds-in-ent.qmd
      - chapters/sec4/4-2-ent-networks.qmd
      - chapters/sec4/4-3-auth.qmd
      - chapters/sec4/4-4-ent-servers.qmd

  appendices:
    - chapters/append/auth.qmd
    - chapters/append/lab-map.qmd
    - chapters/append/cheatsheets.qmd

#bibliography: references.bib

execute:
  eval: false

format:
  html:
    theme: flatly
    code-line-numbers: true

filters:
   - include-code-files

editor: visual

