project:
  type: book

book:
  title: "DevOps for Data Science"
  author: "Alex K Gold"
  page-footer:
    left: "Copyright 2022, Alex K Gold"
    right:
      - icon: github
        href: https://github.com/akgold/do4ds
      - icon: twitter
        href: https://twitter.com/alexkgold
  search: true
  site-url: https://do4ds.com
  repo-url: https://github.com/akgold/do4ds
  repo-actions: [edit]
  sharing: [twitter, facebook]
  google-analytics: "G-BTSMMRMH08"
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - part: chapters/sec1/1-0-sec-intro.qmd
      chapters:
      - chapters/sec1/1-1-code-promotion.qmd
      - chapters/sec1/1-2-env-as-code.qmd
      - chapters/sec1/1-3-data-arch.qmd
      - chapters/sec1/1-4-apis.qmd
      - chapters/sec1/1-5-monitor-log.qmd
    - part: chapters/sec2/2-0-sec-intro.qmd
      chapters:
      - chapters/sec2/2-1-terminal.qmd
      - chapters/sec2/2-2-ssh.qmd
      - chapters/sec2/2-3-cmd-line.qmd
      - chapters/sec2/2-4-docker.qmd
    - part: chapters/sec3/3-0-sec-intro.qmd
      chapters:
      - chapters/sec3/3-1-cloud.qmd
      - chapters/sec3/3-2-linux-admin.qmd
      - chapters/sec3/3-3-networking.qmd
      - chapters/sec3/3-4-dns.qmd
      - chapters/sec3/3-5-ssl.qmd
      - chapters/sec3/3-6-servers.qmd
    - part: chapters/sec4/4-0-sec-intro.qmd
      chapters:
      - chapters/sec4/4-1-os-ds-in-ent.qmd
      - chapters/sec4/4-2-ent-networks.qmd
      - chapters/sec4/4-3-auth.qmd
      - chapters/sec4/4-4-ent-servers.qmd


  appendices:
    - chapters/append/docker-cheatsheet.qmd
    - chapters/append/auth.qmd

#bibliography: references.bib

format:
  html:
    theme: flatly
    code-line-numbers: true

filters:
   - include-code-files

editor: visual

