# Welcome! {.unnumbered}

This is the website for the book *DevOps for Data Science*, currently in
draft form.

::: callout-warning
This book is very much still a work in progress.

The content is mostly here, but I am still rewriting, polishing, and
rearranging.

Content is likely to move from section to section and chapter to
chapter.

Links are likely to break.

Thanks for your patience.
:::

In this book, you'll learn about DevOps conventions, tools, and
practices that can be useful to you as a data scientist. You'll also
learn how to work better with the IT/Admin team at your organization,
and even how to do a little server administration of your own if you're
pressed into service.

This website is (and always will be) **free to use**, and is licensed
under the [Creative Commons Attribution-NonCommercial-NoDerivs
3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/us/) license.

If you'd like a **physical copy** of the book, they will be available
once it's finished!

## Software information {.unnumbered}

I used the **knitr**\index{knitr} package [@xie2015] and the
**quarto**\index{quarto} package [@quarto] to compile my book.

This book is published to the web using GitHub Actions from
[rOpenSci](https://github.com/orchid00/actions_sandbox).

## About the Author

Alex Gold is the Director of Solutions Engineering at [Posit](posit.co),
formerly RStudio.

The Solutions Engineering team works with Posit's customers to help them
deploy, configure, and use Posit's professional software and open-source
tooling in R and Python.

In his free time, he enjoys landscaping, handstands, and Tai Chi.

He occasionally blogs about data, management, and leadership at
[alexkgold.space](http://alexkgold.space).

## Acknowledgments {.unnumbered}

I have so many people to thank for their help in getting this book out
the door.

The biggest thanks to current and former members of the Solutions
Engineering Team at Posit, who taught me so much about DevOps, Data
Science, and how to be a great team.

Thanks to my family, especially my brother, who is a great brother and
cared enough about this project to insist he appear in the
acknowledgments.

Thanks to Randi Cohen at Taylor and Francis, who has been great to work
with, and to my editor, Linda Kahn, who's always been more than an
editor to me.

Most of all, thanks to Shoshana for helping me live my best life.

Huge thanks to the R4DS bookclub, especially Jon Harmon, Gus Lipkin, and
Tinashe Michael Tapera, who read an early (and rough!) copy of this book
and gave me amazing feedback.

Thanks to all others who provided improvements that ended up in this
book (in alphabetical order): Carl Boettinger, Jon Harmon, Gus Lipkin,
and Leungi.

## Color palette

Tea Green: #CAFFDO

Steel Blue: #3E7CB1

Kombu Green: #273c2c

Bright Maroon: #B33951

Sandy Brown: #FCAA67
