# Cheatsheets {#sec-append-cheat}

## Environments as Code

### Checking library + repository status

+--------------------------------------+---------------+---------------+
| Step                                 | R Command     | Python        |
|                                      |               | Command       |
+======================================+===============+===============+
| Check whether library in sync with   | `re           | None          |
| lockfile.                            | nv::status()` |               |
+--------------------------------------+---------------+---------------+

### Creating and Using a Standalone Project Library

Make sure you're in a standalone project library.

+---------------------+---------------------+---------------------+
| Step                | R Command           | Python Command      |
+=====================+=====================+=====================+
| Make sure you've    | `in s t a l l       | Included w/ Python  |
| got                 | . packages("renv")` | 3.5+                |
| `{r  env}/{venv}`.  |                     |                     |
+---------------------+---------------------+---------------------+
| Create a standalone | `renv::init()`      | `p y t              |
| library.            |                     | h on -m venv <dir>` |
|                     |                     |                     |
|                     |                     | Convention:         |
|                     |                     | `u s                |
|                     |                     | e  .venv for <dir>` |
+---------------------+---------------------+---------------------+
| Activate project    | `renv::activate()`  | `sou r c e < d      |
| library.            |                     | i r> /bin/activate` |
|                     | Happens             |                     |
|                     | automatically if    |                     |
|                     | using projects.     |                     |
+---------------------+---------------------+---------------------+
| Install packages as | `ins t a l l .      | `pyth o n - m       |
| normal.             | p ackages("<pkg>")` | p ip install <pkg>` |
+---------------------+---------------------+---------------------+
| Snapshot package    | `renv::snapshot()`  | `p ip fr e e z e    |
| state.              |                     | > requirements.txt` |
+---------------------+---------------------+---------------------+
| Exit project        | Leave R project.    | `deactivate`        |
| environment.        |                     |                     |
+---------------------+---------------------+---------------------+

### Collaborating on someone else's project

Start by downloading the project into a directory on your machine.

+---------------------+---------------------+---------------------+
| Step                | R Command           | Python Command      |
+=====================+=====================+=====================+
| Move into project   | `set wd             | `cd <project-dir>`  |
| directory.          | ( "<project-dir>")` |                     |
|                     |                     |                     |
|                     | Or just open R      |                     |
|                     | project in RStudio. |                     |
+---------------------+---------------------+---------------------+
| Create project      | `renv::init()`      | `py t               |
| environment.        |                     | h on -m venv <dir>` |
|                     |                     |                     |
|                     |                     | Recommend:          |
|                     |                     | `u s                |
|                     |                     | e  .venv for <dir>` |
+---------------------+---------------------+---------------------+
| Enter project       | Happens             | `source < d         |
| environment.        | automatically or    | i r> /bin/activate` |
|                     | `renv::activate()`  |                     |
+---------------------+---------------------+---------------------+
| Restore packages.   | Happens             | `pip install -      |
|                     | automatically or    | r requirements.txt` |
|                     | `renv::restore()`   |                     |
+---------------------+---------------------+---------------------+


## HTTP Code Cheatsheet {#cheat-http}

As you work more with HTTP traffic, you'll learn some of the common
codes. Here's a cheatsheet for some of the most frequent you'll see.

| Code            | Meaning                                                                                                                                                    |
|----------------------|--------------------------------------------------|
| `200`           | Everyone's favorite, a successful response.                                                                                                                |
| `3xx`           | Your query was redirected somewhere else, usually ok.                                                                                                      |
| `4xx`           | Errors with the request                                                                                                                                    |
| `400`           | Bad request. This isn't a request the server can understand.                                                                                               |
| `401` and `403` | Unauthorized or forbidden. Required authentication hasn't been provided.                                                                                   |
| `404`           | Not found. There isn't any content to access here.                                                                                                         |
| `5xx`           | Errors with the server once your request got there.                                                                                                        |
| `500`           | Generic server-side error. Your request was received, but there was an error processing it.                                                                |
| `504`           | Gateway timeout. This means that a proxy or gateway between you and the server you're trying to access timed out before it got a response from the server. |

## Cheatsheet: Git {#cheat-git}

| Command                         | What it Does                                           |
|---------------------------------|--------------------------------------------------------|
| `git clone <remote>`            | Clone a remote repo -- make sure you're using SSH URL. |
| `git add <files/dir>`           | Add files/dir to staging area.                         |
| `git commit -m <message>`       | Commit your staging area.                              |
| `git push origin <branch>`      | Push to a remote.                                      |
| `git pull origin <branch>`      | Pull from a remote.                                    |
| `git checkout <branch name>`    | Checkout a branch.                                     |
| `git checkout -b <branch name>` | Create and checkout a branch.                          |
| `git branch -d <branch name>`   | Delete a branch.                                       |



## Docker {#cheat-docker}

### Docker CLI Commands

+------------+------------+--------------+-----------------------------+
| Stage      | Command    | What it does | Notes and helpful options   |
+============+============+==============+=============================+
| Build      | `dock er   | Builds a     | `-t <name:tag>` provide a   |
|            | build <d i | directory    | name to the container.      |
|            |  rectory>` | containing a | `tag` is optional, defaults |
|            |            | Dockerfile   | to `latest`.                |
|            |            | into an      |                             |
|            |            | image.       |                             |
+------------+------------+--------------+-----------------------------+
| Move       | `do        | Push a       |                             |
|            | cker pus h | container to |                             |
|            |   <image>` | a registry.  |                             |
+------------+------------+--------------+-----------------------------+
| Move       | `do        | Pull a       | Rarely used because `run`   |
|            | cker pul l | container    | pulls the container if      |
|            |   <image>` | from a       | needed.                     |
|            |            | registry.    |                             |
+------------+------------+--------------+-----------------------------+
| Run        | `d         | Run a        | See flags in next table.    |
|            | ocker ru n | container.   |                             |
|            |   <image>` |              |                             |
+------------+------------+--------------+-----------------------------+
| Run        | `dock er   | Stop a       | `docker kill` can be used   |
|            |  stop <c o | running      | if `stop` fails.            |
|            |  ntainer>` | container.   |                             |
+------------+------------+--------------+-----------------------------+
| Run        | `d         | List         | Useful to get running       |
|            |  ocker ps` | containers.  | container id to do things   |
|            |            |              | to it.                      |
+------------+------------+--------------+-----------------------------+
| Run        | `doc ker   | Run a        | Basically always used to    |
|            | exec <c on | command      | open a shell in a container |
|            |  tainer> < | inside a     | with                        |
|            |  command>` | running      | `docker exec                |
|            |            | container.   | -it  <container> /bin/bash` |
+------------+------------+--------------+-----------------------------+
| Run        | `dock er   | Views logs   |                             |
|            |  logs <c o | for a        |                             |
|            |  ntainer>` | container.   |                             |
+------------+------------+--------------+-----------------------------+

### Flags for `docker run`

+--------------+--------------------+---------------------------------+
| Flag         | Effect             | Notes                           |
+==============+====================+=================================+
| `--          | Give a name to the | Optional. Will be auto-assigned |
| name <name>` | running container. | if not provided.                |
+--------------+--------------------+---------------------------------+
| `--rm`       | Remove container   | Don't use in production. You    |
|              | when its stopped.  | probably want to inspect failed |
|              |                    | containers.                     |
+--------------+--------------------+---------------------------------+
| `-d`         | Detach container   | Almost always used in           |
|              | (don't block the   | production.                     |
|              | terminal).         |                                 |
+--------------+--------------------+---------------------------------+
| `-p <p       | Publish port from  | Needed if you want to access an |
| ort>:<port>` | inside container   | app or API running inside the   |
|              | to outside.        | container.                      |
+--------------+--------------------+---------------------------------+
| `-v          | Mount volume into  |                                 |
| <dir>:<dir>` | the container.     |                                 |
+--------------+--------------------+---------------------------------+

: *Reminder: Order for `-p` and `-v` is `<host>:<container>`*

### Dockerfile Commands

These are the commands that go in a Dockerfile when you're building it.

+-------------+-------------------------------------+-----------------+
| Command     | Purpose                             | Example         |
+=============+=====================================+=================+
| `FROM`      | Indicate base container.            | `FROM rocke     |
|             |                                     | r /r-ver:4.1.0` |
+-------------+-------------------------------------+-----------------+
| `RUN`       | Run a command when building.        | `RUN a          |
|             |                                     | p t-get update` |
+-------------+-------------------------------------+-----------------+
| `COPY`      | Copy from build directory into the  | `COPY . /app/`  |
|             | container.                          |                 |
+-------------+-------------------------------------+-----------------+
| `CMD`       | Specify the command to run when the | `CMD qu         |
|             | container starts.                   | a rto render .` |
+-------------+-------------------------------------+-----------------+

## Cloud Services

TODO: finish

+------------+-----------------------------+------------+------------+
| Service    | AWS                         | Azure      | GCP        |
+============+=============================+============+============+
| NAS        | EFS (Elastic File System)   | Azure File | Filestore  |
|            | or FSx                      |            |            |
+------------+-----------------------------+------------+------------+
| Kubernetes | EKS (Elastic Kubernetes     | AKS (Azure | GKE        |
| cluster    | Service) or Fargate         | Kubernetes | (Google    |
|            |                             | Service)   | Kubernetes |
|            |                             |            | Engine)    |
+------------+-----------------------------+------------+------------+
| Run a      | ECS (Elastic Container      | Azure      | Google App |
| container  | Service) or Elastic         | Container  | Engine     |
| /a         | Beanstalk                   | Apps       |            |
| pplication |                             |            |            |
+------------+-----------------------------+------------+------------+
| Run an API | Lambda                      | Azure      | Google     |
|            |                             | Functions  | Cloud      |
|            |                             |            | Functions  |
+------------+-----------------------------+------------+------------+
| Database   | RDS or \| Azure \| Google   |            |            |
|            | Cloud Redshif \| Database   |            |            |
|            | \| SQL t\[\^2-1-cloud-8\]   |            |            |
|            | \| \| \|                    |            |            |
+------------+-----------------------------+------------+------------+
| ML         | SageMaker                   | Azure ML   | Vertex AI  |
| Platform   |                             |            |            |
+------------+-----------------------------+------------+------------+

## Command Line {#cheat-cli}

### General Command Line

| Symbol          | What it is                        |
|-----------------|-----------------------------------|
| `man <command>` | Open manual for `command`         |
| `q`             | Quit the current screen           |
| `\`             | Continue bash command on new line |
| `ctrl + c`      | Quit current execution            |

### Linux Navigation

+---------------+-------------------------+-------------------------+
| Command       | What it does/is         | Notes + Helpful options |
+===============+=========================+=========================+
| `/`           | System root or file     |                         |
|               | path separator          |                         |
+---------------+-------------------------+-------------------------+
| `.`           | current working         |                         |
|               | directory               |                         |
+---------------+-------------------------+-------------------------+
| `..`          | Parent of working       |                         |
|               | directory               |                         |
+---------------+-------------------------+-------------------------+
| `~`           | Home directory of the   |                         |
|               | current user            |                         |
+---------------+-------------------------+-------------------------+
| `ls <dir>`    | List objects in a       | `-l` - format as list   |
|               | directory               |                         |
|               |                         | `-a` - all (include     |
|               |                         | hidden files that start |
|               |                         | with `.`)               |
+---------------+-------------------------+-------------------------+
| `pwd`         | Print working directory |                         |
+---------------+-------------------------+-------------------------+
| `cd <dir>`    | Change directory        | Can use relative or     |
|               |                         | absolute paths          |
+---------------+-------------------------+-------------------------+

### Reading Text Files

+---------------------+---------------------+---------------------+
| Command             | What it does        | Notes + Helpful     |
|                     |                     | options             |
+=====================+=====================+=====================+
| `cat <file>`        | Print a file from   |                     |
|                     | the top.            |                     |
+---------------------+---------------------+---------------------+
| `less <file>`       | Print a file, but   | Can be very helpful |
|                     | just a little.      | to look at a few    |
|                     |                     | rows of csv.        |
|                     |                     |                     |
|                     |                     | Lazily reads lines, |
|                     |                     | so can be *much*    |
|                     |                     | faster than `cat`   |
|                     |                     | for big files.      |
+---------------------+---------------------+---------------------+
| `head <file>`       | Look at the         | Defaults to 10      |
|                     | beginning of a      | lines, can specify  |
|                     | file.               | a different number  |
|                     |                     | with `-n <n>`.      |
+---------------------+---------------------+---------------------+
| `tail <file>`       | Look at the end of  | Useful for logs     |
|                     | a file.             | where the newest    |
|                     |                     | part is last.       |
|                     |                     |                     |
|                     |                     | The `-f` flag is    |
|                     |                     | useful to follow    |
|                     |                     | for a live view.    |
+---------------------+---------------------+---------------------+
| `g r                | Search a file using | Writing regex can   |
|   e p <expression>` | regex.              | be a pain. I        |
|                     |                     | suggest testing     |
|                     |                     | expressions on      |
|                     |                     | regex101.com.       |
|                     |                     |                     |
|                     |                     | Often useful in     |
|                     |                     | combination with    |
|                     |                     | the pipe.           |
+---------------------+---------------------+---------------------+
| `|`                 | The pipe            |                     |
+---------------------+---------------------+---------------------+

### Manipulating Files

+--------------------+---------------------+---------------------+
| Command            | What it does/is     | Notes + Helpful     |
|                    |                     | Options             |
+====================+=====================+=====================+
| `rm <path>`        | Remove              | `-r` - recursively  |
|                    |                     | remove everything   |
|                    |                     | below a file path   |
|                    |                     |                     |
|                    |                     | `-f` - force -      |
|                    |                     | don't ask for each  |
|                    |                     | file                |
|                    |                     |                     |
|                    |                     | **Be very careful,  |
|                    |                     | it's permanent**    |
+--------------------+---------------------+---------------------+
| `                  | Copy                |                     |
| c   p <from> <to>` |                     |                     |
+--------------------+---------------------+---------------------+
| `                  | Move                |                     |
| m   v <from> <to>` |                     |                     |
+--------------------+---------------------+---------------------+
| `*`                | Wildcard            |                     |
+--------------------+---------------------+---------------------+
| `mkdir`/`rmdir`    | Make/remove         | `-p` - create any   |
|                    | directory           | parts of path that  |
|                    |                     | don't exist         |
+--------------------+---------------------+---------------------+

### Move things to/from server

+--------------+-------------------------+-------------------------+
| Command      | What it does            | Notes + Helpful options |
+==============+=========================+=========================+
| `tar`        | Create/extract archive  | Almost always used with |
|              | file                    | flags.                  |
|              |                         |                         |
|              |                         | Create is usually       |
|              |                         |                         |
|              |                         | `tar -czf < a  r        |
|              |                         | c hive name> <file(s)>` |
|              |                         |                         |
|              |                         | Extract is usually      |
|              |                         |                         |
|              |                         | `t  a                   |
|              |                         | r  -xfv <archive name>` |
+--------------+-------------------------+-------------------------+
| `scp`        | Secure copy via `ssh`   | Run on laptop to server |
|              |                         |                         |
|              |                         | Can use most `ssh`      |
|              |                         | flags (like `-i` and    |
|              |                         | `-v`)                   |
+--------------+-------------------------+-------------------------+

### Write files from the command line

+------------+----------------------+---------------------------------+
| Command    | What it does         | Notes                           |
+============+======================+=================================+
| `touch`    | Creates file if      | Updates last updated to current |
|            | doesn't already      | time if it does exist.          |
|            | exist.               |                                 |
+------------+----------------------+---------------------------------+
| `>`        | Overwrite file       | Creates a new file if it        |
|            | contents             | doesn't exist                   |
+------------+----------------------+---------------------------------+
| `>>`       | Concatenate to end   | Creates a new file if it        |
|            | of file              | doesn't exist                   |
+------------+----------------------+---------------------------------+

### Command Line Text Editors (Vim + Nano)

+-------------+----------------------------+---------------------------+
| Command     | What it does               | Notes + Helpful options   |
+=============+============================+===========================+
| `^`         | Prefix for file command in | Its the `⌘` or `Ctrl`     |
|             | `nano` editor.             | key, not the caret        |
|             |                            | symbol.                   |
+-------------+----------------------------+---------------------------+
| `i`         | Enter insert mode (able to |                           |
|             | type) in `vim`             |                           |
+-------------+----------------------------+---------------------------+
| `escape`    | Enter normal mode          |                           |
|             | (navigation) in `vim`.     |                           |
+-------------+----------------------------+---------------------------+
| `:w`        | Write the current file in  | Can be combined to save   |
|             | `vim` (from normal mode)   | and quit in one, `:wq`    |
+-------------+----------------------------+---------------------------+
| `:q`        | Quit `vim` (from normal    | `:q!` quit without saving |
|             | mode)                      |                           |
+-------------+----------------------------+---------------------------+

## Cheatsheet: Users and Permissions {#cheat-file}

### Users

+--------------------+------------------------------------------------+
| Command            | What it does                                   |
+====================+================================================+
| `su <username>`    | Change to be a different user.                 |
+--------------------+------------------------------------------------+
| `whoami`           | Get username of current user.                  |
+--------------------+------------------------------------------------+
| `id`               | Get full user + group info on current user.    |
+--------------------+------------------------------------------------+
| `passwd`           | Change password.                               |
+--------------------+------------------------------------------------+
| `useradd`          | Add a new user.                                |
+--------------------+------------------------------------------------+
| `u s               | Modify user `username`. `-aG <group>` adds to  |
|  ermod <username>` | a group                                        |
+--------------------+------------------------------------------------+

### Permissions

+--------------+----------------+------------------------------------+
| Command      | What it does   | Helpful options + notes            |
+==============+================+====================================+
| `chm o d     | Modifies       | Number indicates permissions for   |
|  <permissi   | permissions on | user, group, others: add 4 for     |
| ons> <file>` | a file.        | read, 2 for write, 1 for execute,  |
|              |                | 0 for nothing.                     |
+--------------+----------------+------------------------------------+
| `cho w n     | Change the     | Can be used for user or group,     |
|   <user/gr   | owner of a     | e.g. `:my-group`.                  |
| oup> <file>` | file.          |                                    |
+--------------+----------------+------------------------------------+
| `su          | Change active  |                                    |
|  <username>` | user to        |                                    |
|              | `username`.    |                                    |
+--------------+----------------+------------------------------------+
| `sud         | Adopt super    |                                    |
| o <command>` | user           |                                    |
|              | permissions    |                                    |
|              | for the        |                                    |
|              | following      |                                    |
|              | command.       |                                    |
+--------------+----------------+------------------------------------+

## Cheatsheet: `ssh` {#cheat-ssh}

``` bash
ssh <user>@<host>
```

+------------+-----------------------+--------------------------------+
| Flag       | What it does          | Notes                          |
+============+=======================+================================+
| `-v`       | Verbose, good for     | Add more `v`s as you please,   |
|            | debugging.            | `-vv` or `-vvv`.               |
+------------+-----------------------+--------------------------------+
| `-i`       | Choose identity file  | Not necessary with default key |
|            | (private key)         | names.                         |
+------------+-----------------------+--------------------------------+

## Cheatsheet: Linux Admin Commands {#cheat-admin}

### Users

+----------------------+-----------------------------------------------+
| Command              | What it does                                  |
+======================+===============================================+
| `su <username>`      | Change to be a different user.                |
+----------------------+-----------------------------------------------+
| `whoami`             | Get username of current user.                 |
+----------------------+-----------------------------------------------+
| `id`                 | Get full user + group info on current user.   |
+----------------------+-----------------------------------------------+
| `passwd`             | Change password.                              |
+----------------------+-----------------------------------------------+
| `useradd`            | Add a new user.                               |
+----------------------+-----------------------------------------------+
| `use                 | Modify user `username`. `-aG <group>` adds to |
|   r m od <username>` | a group                                       |
+----------------------+-----------------------------------------------+

### Permissions

+---------------+----------------+------------------------------------+
| Command       | What it does   | Helpful options + notes            |
+===============+================+====================================+
| `ch m od      | Modifies       | Number indicates permissions for   |
| <per m i s s  | permissions on | user, group, others: add 4 for     |
| ions> <file>` | a file.        | read, 2 for write, 1 for execute,  |
|               |                | 0 for nothing.                     |
+---------------+----------------+------------------------------------+
| `c h ow n     | Change the     | Can be used for user or group,     |
|  <us e r / g  | owner of a     | e.g. `:my-group`.                  |
| roup> <file>` | file.          |                                    |
+---------------+----------------+------------------------------------+
| `s            | Change active  |                                    |
| u <username>` | user to        |                                    |
|               | `username`.    |                                    |
+---------------+----------------+------------------------------------+
| `s u          | Adopt super    |                                    |
| do <command>` | user           |                                    |
|               | permissions    |                                    |
|               | for the        |                                    |
|               | following      |                                    |
|               | command.       |                                    |
+---------------+----------------+------------------------------------+

### Install applications (Ubuntu)

+----------------------------------+-----------------------------------+
| **Command**                      | **What it does**                  |
+----------------------------------+-----------------------------------+
| `apt-get u p                     | Fetch and install upgrades to     |
|   d a t e && apt-get upgrade -y` | system packages                   |
+----------------------------------+-----------------------------------+
| `a p t-get install <package>`    | Install a system package.         |
+----------------------------------+-----------------------------------+
| `wget`                           | Download a file from a URL.       |
+----------------------------------+-----------------------------------+
| `gdebi`                          | Install local `.deb` file.        |
+----------------------------------+-----------------------------------+

### Storage

+--------------+-------------------------+-------------------------+
| Command      | What it does            | Helpful options         |
+==============+=========================+=========================+
| `df`         | Check storage space on  | `-h` for human readable |
|              | device.                 | file sizes.             |
+--------------+-------------------------+-------------------------+
| `du`         | Check size of files.    | Most likely to be used  |
|              |                         | as                      |
|              |                         | `d                      |
|              |                         | u  - h <dir> | sort -h` |
|              |                         |                         |
|              |                         | Also useful to combine  |
|              |                         | with `head`.            |
+--------------+-------------------------+-------------------------+

### Processes

+-------------+--------------------+-----------------------------------+
| Command     | What it does       | Helpful options                   |
+=============+====================+===================================+
| `top`       | See what's running |                                   |
|             | on the system.     |                                   |
+-------------+--------------------+-----------------------------------+
| `ps aux`    | See all system     | Consider using `--sort` and pipe  |
|             | processes.         | into `head` or `grep`             |
+-------------+--------------------+-----------------------------------+
| `kill`      | Kill a system      | `-9` to force kill immediately    |
|             | process.           |                                   |
+-------------+--------------------+-----------------------------------+

### Networking

+----------------+-------------------+--------------------------------+
| Command        | What it does      | Helpful options                |
+================+===================+================================+
| `netstat`      | See ports and     | Usually used with `-tlp`, for  |
|                | services using    | tcp listening applications,    |
|                | them.             | including `pid`                |
+----------------+-------------------+--------------------------------+
| `ssh - L       | Port forwards a   | Choose local port to match     |
|  <port>:<ip>:  | remote port on    | remote port. Remote `ip` is    |
| <port> <host>` | host to local.    | usually `localhost`.           |
+----------------+-------------------+--------------------------------+

### The path

+-------------------------------+-----------------------------------+
| Command                       | What it does                      |
+===============================+===================================+
| `which <command>`             | Finds the location of the binary  |
|                               | that runs when you run `command`. |
+-------------------------------+-----------------------------------+
| \                             | Creates a symlink from file at    |
| \`ln -s \< lo cation to       | `location to link` to             |
| link\>                        | `location of symlink`.            |
|                               |                                   |
| : \< l ocation of symlink\>\` |                                   |
+-------------------------------+-----------------------------------+

## Cheatsheet: IP Addresses and Ports {#cheat-ports}

### Special IP Addresses

+---------------+----------------------------------------------------+
| Code          | Meaning                                            |
+===============+====================================================+
| 127.0.0.1     | `localhost` or loopback -- the machine that        |
|               | originated the request                             |
+---------------+----------------------------------------------------+
| 192.168.x.x   | Protected address blocks used for private IP       |
|               | addresses.                                         |
| 172.16.x.x.x  |                                                    |
|               |                                                    |
| 10.x.x.x      |                                                    |
+---------------+----------------------------------------------------+

### Special Ports

All ports below 1024 are reserved for server tasks and cannot be
assigned to admin-controlled services.

| Protocol/Application | Default Port |
|----------------------|--------------|
| HTTP                 | 80           |
| HTTPS                | 443          |
| SSH                  | 22           |
| PostgreSQL           | 5432         |
| RStudio Server       |              |
| Shiny Server         |              |
| JupyterHub           |              |

## Cheatsheet: Debugging Tips

If things are going poorly on your server, here are some steps you might
take to try to troubleshoot.

### Check storage usage

A common culprit for weird server behavior is running out of storage
space. There are two handy commands for monitoring the amount of storage
you've got -- `du` and `df`. These commands are almost always used with
the `-h` flag to put file sizes in human-readable formats.

`df`, for disk free, shows the capacity left on the device where the
directory sits.

For example, here's the result of running the `df` command on the
chapters directory on my laptop that includes this chapter.

``` bash
 ❯ df -h chapters                                                    
Filesystem     Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk3s5  926Gi  163Gi  750Gi    18% 1205880 7863468480    0%   /System/Volumes/Data
```

So you can see that the chapters folder lives on a disk called
`/dev/disk3s5` that's a little less than 1Tb and is 18% full -- no
problem. On a server this can be really useful to know, because it's
quite easy to switch a disk out for a bigger one in the same spot.

If you've figured out that a disk is full and need to figure out where
the culprits are, the `du` can be useful. `du`, short for disk usage,
gives you the size of individual files inside a directory. It's
particularly useful in combination with the `sort` command.

For example, here's the result of running `du` on the `chapters`
directory where the text files for this book live.

``` bash
 ❯ du -h chapters | sort -h                                      
 44K    chapters/sec2/images-servers
124K    chapters/sec3/images-scaling
156K    chapters/sec2/images
428K    chapters/sec2/images-traffic
656K    chapters/sec1/images-code-promotion
664K    chapters/sec1/images-docker
1.9M    chapters/sec1/images-repro
3.4M    chapters/sec1
3.9M    chapters/sec3/images-auth
4.1M    chapters/sec3
4.5M    chapters/sec2/images-networking
5.3M    chapters/sec2
 13M    chapters
```

So if I were thinking about cleaning up this directory, I could see that
my `images-networking` directory in `sec2` is the biggest single
bottom-level directory. If you find yourself needing to find big files
on your Linux server, it's worth spending some time with the help pages
for `du`. There are lots of really useful options.

`du` is useful for identifying large files and directories on a server.

### Look at what's running

A running program is a *process*. For example, when you type `python` on
the command line to open a REPL, that starts a single Python process. If
you were to start a second terminal session and run `python` again,
you'd have a second Python process.

Complicated programs often involves multiple than one process. For
example, running the RStudio IDE involves (at minimum) one process for
the IDE itself and one for the R session that it uses in the background.
The relationships between these different processes is mostly hidden
from you -- the end user.

As a server admin, finding runaway processes, killing them, and figuring
out how to prevent the them from happening again is a pretty common
task. Runaway processes usually misbehave by using up the entire CPU or
filling up the entire machine's RAM.

Like users and groups have ids, each process has a numeric process id
(`pid`). Each process also has an owner -- this can be either a service
account or a real user. If you've got a rogue process, the pattern is to
try to find the process and make note of its `pid`. Then you can
immediately end the process by `pid` with the `kill` command.

So, how do you find a troublesome process?

The `top` command is a good first stop. `top` shows the top
CPU-consuming processes in real time. Here's the `top` output from my
machine as I write this sentence.

``` bash
PID    COMMAND      %CPU TIME     #TH    #WQ  #PORT MEM    PURG   CMPRS PGRP
0      kernel_task  16.1 03:56:53 530/10 0    0     2272K  0B     0B    0
16329  WindowServer 16.0 01:53:20 23     6    3717  941M-  16M+   124M  16329
24484  iTerm2       11.3 00:38.20 5      2    266-  71M-   128K   18M-  24484
29519  top          9.7  00:04.30 1/1    0    36    9729K  0B     0B    29519
16795  Magnet       3.1  00:39.16 3      1    206   82M    0B     39M   16795
16934  Arc          1.8  18:18.49 45     6    938   310M   144K   61M   16934
16456  Messages     1.7  06:58.27 4      1    603   138M   2752K  63M   16456
1      launchd      1.7  13:41.03 4/1    3/1  3394+ 29M    0B     6080K 1
573    diagnosticd  1.4  04:31.97 3      2    49    2417K  0B     816K  573
16459  zoom.us      1.3  66:38.37 30     3    2148  214M   384K   125M  16459
16575  UniversalCon 1.3  01:15.89 2      1    131   12M    0B     2704K 16575
```

In most instances, the first three columns are the most useful. You've
got the name of the process (`COMMAND`) and how much CPU its using.
Right now, nothing is using very much CPU. If I were to find something
concerning -- perhaps an R process that is using 500% of CPU -- I would
want to take notice of its `pid` to kill it with `kill`.

::: callout-note
### So much CPU?

For `top` (and most other commands), CPU is expressed as a percent of
*single core* availability. So, on a modern machine with multiple cores,
it's very common to see CPU totals well over 100%. Seeing a single
process using over 100% of CPU is rarer.
:::

The `top` command takes over your whole terminal. You can exit with
`Ctrl + c`.

Another useful command for finding runaway processes is `ps aux`. It
lists a snapshot of all processes running on the system, along with how
much CPU and RAM they're using. You can sort the output with the
`--sort` flag and specify sorting by cpu with `--sort -%cpu` or by
memory with `--sort -%mem`.

Because `ps aux` returns *every* running process on the system, you'll
probably want to pipe the output into `head`.

Another useful way to use `ps aux` is in combination with `grep`. If you
pretty much know what the problem is -- often this might be a runaway R
or Python process -- `ps aux | grep <name>` can be super useful to get
the `pid`.

For example, here are the RStudio processes currently running on my
system.[^cheatsheets-1]

[^cheatsheets-1]: This command actually cuts off the header line of the
    table. What I actually ran was `ps aux | grep "RStudio\|USER"`.

``` bash
 > ps aux | grep "RStudio"                                                                                      [10:21:18]
USER               PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND
alexkgold        23583   0.9  1.7 37513368 564880   ??  S    Sat09AM  17:15.27 /Applications/RStudio.app/Contents/MacOS/RStudio
alexkgold        23605   0.5  0.4 36134976 150828   ??  S    Sat09AM   1:58.16 /Applications/RStudio.app/Contents/MacOS/rsession --config-file none --program-mode desktop 
```

### Make sure the right ports are open

Networking is a complicated topic, which we'll approach with great
detail in [Chapter @sec-networking]. Most often, you'll want to check
that the application you're running is actually accessible to the
outside world, assuming you want it to be.

The main command to help you see what ports are being used and by what
services is the `netstat` command. `netstat` returns the services that
are running and their associated ports. `netstat` is generally most
useful with the `-tlp` flags to show programs that are listening and the
programs associated.

Sometimes you *know* you've got a service running on your machine, but
you just can't seem to get the networking working. It can be useful to
access the service directly without having to deal with networking.

SSH port forwarding allows you to take the output of a port on a remote
server, route it through SSH, and display it as if it were on a local
port. For example, let's say you've got RStudio Server running on my
server but the web interface isn't working. If you've got SSH working
properly, you can double check that the service is working and the issue
really is networking.

I find that the syntax for port forwarding completely defies my memory
and I have to google it every time I use it. For the kind of port
forwarding you'll use most often in debugging, you'll use the `-L` flag
to get a remote port locally.

`ssh -L <local port>:<remote ip>:<remote port> <ssh hostname>`

The local would be your laptop and the remote your server, so if you had
RStudio Server running on a server on port `3939`. Then you could run
`ssh -L 3939:localhost:3939 my-user@my-ds-workbench.com`. To get
whatever is at port `3939` on the server (hopefully RStudio Workbench!)
by going to `localhost:3939` in the laptop's browser.

Most often, you'll use the same port locally and on the remote and the
remote ip will be `localhost`.

### Check your path

Let's say you want to open Python on your command line. One option would
be to type the complete path to a Python install every time. For
example, I've got a version of Python in `/usr/bin`, so
`/usr/bin/python3` works.

But in most cases, it's nice to just type `python3` and have the right
version open up.

``` bash
$ python3
Python 3.9.6 (default, May  7 2023, 23:32:45) 
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

In some cases, this isn't optional. Certain applications will rely on
others being available, like RStudio needing to find R. Or Jupyter
Notebook finding your Python kernels.

So how does the operating system know where to find those applications
and files?

If you ever want to check which actual executable is being used by a
command, you can use the `which` command. For example, on my system this
is the result of `which python3`.

``` bash
 ❯ which python3                                                    
/usr/bin/python3
```

The operating system knows how to find the actual runnable programs on
your system via the *path*. The path is a set of directories that the
system knows to search when it tries to run a path. The path is stored
in an environment variable conveniently named `PATH`.

You can check your path at any time by echoing the `PATH` environment
variable with `echo $PATH`. On my MacBook, this is what the path looks
like.

``` bash
 ❯ echo $PATH                                                      
/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

When you install a new piece of software you'll need to add it two the
path. Say I was to install a new version of Python in `/opt/python`.
That's not on my `PATH`, so my system wouldn't be able to find it.

I can get it on the path in one of two ways -- the first option would be
to add `/opt/python` to my `PATH` every time a terminal session starts
usually via a file in `/etc` or the `.zshrc`. The other option is to
create a *symlink* to the new application in a directory already on the
`PATH`. A symlink does what it sounds like -- creates a way to link to a
file from a different directory without moving it.

Symlinks are created with the `ln` command.

## Comprehension Questions

1.  How would you do the following?
    1.  Find and kill the process IDs for all running `rstudio-server`
        processes.

    2.  Figure out which port `JupyterHub` is running on.

    3.  Create a file called `secrets.txt`, open it with vim, write
        something in, close and save it, and make it so that only you
        can read it.
