# Lab Map {#sec-append-lab}

This section aims to clarify the relationship between the assets you'll
make in each portfolio exercise and labs in this book.

+----------------------+-----------------------------------------------------------------------------------+
| Chapter              | Lab Activity                                                                      |
+======================+===================================================================================+
| [@sec-env-as-code]:  | Create a Quarto site that uses `{renv}` and `{venv}` to create standalone R and   |
| Environments as Code | Python virtual environments. Add an R EDA page and Python modeling.               |
+----------------------+-----------------------------------------------------------------------------------+
| [@sec-proj-arch]:    | Create an API that serves a Python machine-learning model using `{vetiver}` and   |
| Project Architecture | `{fastAPI}`. Call that API from a Shiny App in both R and Python.                 |
+----------------------+-----------------------------------------------------------------------------------+
| [@sec-data-access]:  | Move data into a DuckDB database and serve model predictions from an API.         |
| Data Architecture    |                                                                                   |
+----------------------+-----------------------------------------------------------------------------------+
| [@sec-log-monitor]:  | Add logging to the app from [Chapter @sec-proj-arch].                             |
| Logging and          |                                                                                   |
| Monitoring           |                                                                                   |
+----------------------+-----------------------------------------------------------------------------------+
| [@sec-deployments]:  | Put a static Quarto site up on GitHub Pages using GitHub Actions that renders the |
| Deployments          | project.                                                                          |
+----------------------+-----------------------------------------------------------------------------------+
| [@sec-docker]:       | Put API from [Chapter @sec-proj-arch] into Docker Container.                      |
| Docker               |                                                                                   |
+----------------------+-----------------------------------------------------------------------------------+
| [@sec-cloud]: Cloud  | Stand up an EC2 instance.                                                         |
|                      |                                                                                   |
|                      | Put the model into S3.                                                            |
+----------------------+-----------------------------------------------------------------------------------+
| [@sec-cmd-line]:     | Log into the server with `.pem` key and create SSH key.                           |
| Command Line         |                                                                                   |
+----------------------+-----------------------------------------------------------------------------------+
| [@sec-linux]: Linux  | Create a user on the server and add SSH key.                                      |
| Admin                |                                                                                   |
+----------------------+-----------------------------------------------------------------------------------+
| [@sec-app-admin]:    | Add R, Python, RStudio Server, JupyterHub, API, and App to EC2 instance from      |
| Application Admin    | [Chapter @sec-cloud].                                                             |
+----------------------+-----------------------------------------------------------------------------------+
| [@sec-scale]:        | Resize the server.                                                                |
| Scaling              |                                                                                   |
+----------------------+-----------------------------------------------------------------------------------+
| [@sec-networking]:   | Add proxy (NGINX) to reach all services from the web.                             |
| Networking           |                                                                                   |
+----------------------+-----------------------------------------------------------------------------------+
| [@sec-dns]: DNS      | Add a URL to the EC2 instance. Put the Shiny app into an iFrame on the Quarto     |
|                      | site.                                                                             |
+----------------------+-----------------------------------------------------------------------------------+
| [@sec-ssl]: SSL      | Add SSL/HTTPS to the EC2 instance.                                                |
+----------------------+-----------------------------------------------------------------------------------+
